spring:
  application:
    name: access-management-application
  profiles :
    active: local
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/accessor
    username: postgres
    password: postgres
    properties:
      schema: creds

authentication:
  github:
    api:
      url: https://api.github.com/user
  jwt:
    secret-key : You$hop99Gunitha@2906You$hop99Gunitha@2906You$hop99Gunitha@2906You$hop99Gunitha@2906You$hop99Gunitha@2906
    expiration-ms: 10000